# Form implementation generated from reading ui file 'app1.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1125, 859)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 10, 411, 81))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(80, 70, 891, 131))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(50, 40, 55, 16))
        self.label_2.setObjectName("label_2")
        self.ho_ten = QtWidgets.QLineEdit(parent=self.groupBox)
        self.ho_ten.setGeometry(QtCore.QRect(130, 40, 181, 21))
        self.ho_ten.setObjectName("ho_ten")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(40, 90, 71, 16))
        self.label_3.setObjectName("label_3")
        self.gioi_tinh = QtWidgets.QComboBox(parent=self.groupBox)
        self.gioi_tinh.setGeometry(QtCore.QRect(130, 90, 73, 22))
        self.gioi_tinh.setObjectName("gioi_tinh")
        self.gioi_tinh.addItem("")
        self.gioi_tinh.addItem("")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(80, 220, 981, 191))
        self.groupBox_2.setObjectName("groupBox_2")
        self.ca_fe = QtWidgets.QCheckBox(parent=self.groupBox_2)
        self.ca_fe.setGeometry(QtCore.QRect(40, 60, 81, 20))
        self.ca_fe.setObjectName("ca_fe")
        self.bim_bim = QtWidgets.QCheckBox(parent=self.groupBox_2)
        self.bim_bim.setGeometry(QtCore.QRect(190, 60, 81, 20))
        self.bim_bim.setObjectName("bim_bim")
        self.nguoi_lon = QtWidgets.QSpinBox(parent=self.groupBox_2)
        self.nguoi_lon.setGeometry(QtCore.QRect(140, 110, 42, 22))
        self.nguoi_lon.setObjectName("nguoi_lon")
        self.tre_em = QtWidgets.QSpinBox(parent=self.groupBox_2)
        self.tre_em.setGeometry(QtCore.QRect(140, 150, 42, 22))
        self.tre_em.setObjectName("tre_em")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(40, 110, 81, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(40, 150, 71, 16))
        self.label_5.setObjectName("label_5")
        self.tinh_tien = QtWidgets.QPushButton(parent=self.centralwidget)
        self.tinh_tien.setGeometry(QtCore.QRect(110, 450, 93, 28))
        self.tinh_tien.setObjectName("tinh_tien")
        self.tien = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.tien.setGeometry(QtCore.QRect(220, 450, 131, 31))
        self.tien.setObjectName("tien")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(360, 460, 55, 16))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1125, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.tinh_tien.clicked.connect(self.tt)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ỨNG DỤNG BÁN VÉ "))
        self.groupBox.setTitle(_translate("MainWindow", "THÔNG TIN KHÁCH HÀNG"))
        self.label_2.setText(_translate("MainWindow", "HỌ TÊN "))
        self.label_3.setText(_translate("MainWindow", "GIỚI TÍNH "))
        self.gioi_tinh.setItemText(0, _translate("MainWindow", "Nam"))
        self.gioi_tinh.setItemText(1, _translate("MainWindow", "Nữ"))
        self.groupBox_2.setTitle(_translate("MainWindow", "DỊCH VỤ "))
        self.ca_fe.setText(_translate("MainWindow", "CAFE"))
        self.bim_bim.setText(_translate("MainWindow", "BIM BIM"))
        self.label_4.setText(_translate("MainWindow", "NGƯỜI LỚN"))
        self.label_5.setText(_translate("MainWindow", "TRẺ EM"))
        self.tinh_tien.setText(_translate("MainWindow", "TIỀN TRẢ "))
        self.label_6.setText(_translate("MainWindow", "VND"))
    def tt(self):
        price = {
            "ca_fe" : 100000,
            "bim_bim" : 50000,
            "nguoi_lon": 200000,
            "tre_em": 50000
                }
        tcf = 0
        if self.ca_fe.checkState() !=0:          # checkbox cafe
            tcf = price["ca_fe"]

        tbb = 0
        if self.bim_bim.checkState() != 0:       # checkbox bimbim
            tcf = price["bim_bim"]

        tnl = int(self.nguoi_lon.text())*price["nguoi_lon"]      # Lấy giá trị ở ô text người lớn
        tte = int(self.tre_em.text())*price["tre_em"]            # Lấy giá trị ở ô text trẻ em

        sum = tcf + tbb + tnl + tte

        # Đưa tien vao khung tien
        self.tien.setText(str(sum))

        # Bật cửa sổ tiền trả
        msg = QtWidgets.QMessageBox()
        msg.setInformativeText(f'Tổng tiền phải trả:{sum}')
        msg.exec()




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
