# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1004, 735)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(190, 50, 581, 411))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.Button_load_data = QtWidgets.QPushButton(self.centralwidget)
        self.Button_load_data.setGeometry(QtCore.QRect(190, 480, 141, 61))
        self.Button_load_data.setObjectName("Button_load_data")
        self.comboBox_choose_database = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_choose_database.setGeometry(QtCore.QRect(190, 560, 141, 41))
        self.comboBox_choose_database.setObjectName("comboBox_choose_database")
        self.comboBox_choose_database.addItem("")
        self.comboBox_choose_database.addItem("")
        self.comboBox_choose_table = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_choose_table.setGeometry(QtCore.QRect(360, 560, 141, 41))
        self.comboBox_choose_table.setObjectName("comboBox_choose_table")
        self.comboBox_choose_table.addItem("")
        self.comboBox_choose_table.addItem("")
        self.Button_update = QtWidgets.QPushButton(self.centralwidget)
        self.Button_update.setGeometry(QtCore.QRect(580, 480, 161, 41))
        self.Button_update.setObjectName("Button_update")
        self.textEdit_data = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_data.setGeometry(QtCore.QRect(580, 540, 161, 61))
        self.textEdit_data.setObjectName("textEdit_data")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1004, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_load_data.setText(_translate("MainWindow", "LOAD DATA"))
        self.comboBox_choose_database.setItemText(0, _translate("MainWindow", "qlsv1"))
        self.comboBox_choose_database.setItemText(1, _translate("MainWindow", "qlsv"))
        self.comboBox_choose_table.setItemText(0, _translate("MainWindow", "sinh_vien"))
        self.comboBox_choose_table.setItemText(1, _translate("MainWindow", "sinh_vien_1"))
        self.Button_update.setText(_translate("MainWindow", "UPDATE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
